#!/bin/bash
# Check for prerequisites
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run using sudo!"
    exit 1
fi

# Copy n8n config
mkdir -p /opt/so/saltstack/local/salt/n8n
cp -av salt/n8n/* /opt/so/saltstack/local/salt/n8n

# Copy nginx config
cp salt/nginx/etc/nginx.conf /opt/so/saltstack/local/salt/nginx/etc/nginx.conf

# Copy utility scripts
cp -av salt/common/tools/sbin/so-n8n-* /opt/so/saltstack/default/salt/common/tools/sbin/

# Restart nginx to load new config
so-nginx-restart --force

# Apply common state to pull in utility scripts
salt-call saltutil.kill_all_jobs && salt-call state.apply common

# Start n8n
so-n8n-start --force

# Copy top file - TODO
# cp salt/top.sls /opt/so/saltstack/local/salt/top.sls

echo "Done!"
echo "Access n8n by navigating to https://MANAGERIP/n8n"
